### ISSUE TITLE
puppet 可以支持 port 和 host 配置吗

### ISSUE THREAD

**Issue by lblblong** [wechatferry/wechatferry#11]
我的服务是运行在 linux 上的，现在是想在本地的 windows 上跑一个 wechatferry 的 service 模式

我看了文档，但是不太清楚怎么通过 port 和 host 连上去，是要自己实例化一个 WechatferrySDK 传过去吗，有没有示例代码

![image](https://github.com/user-attachments/assets/c8cb3825-cbe5-4aa7-b817-33efa280cde9)

**Comment by KeJunMao** [comment]
这里不是 `@zippybee/wechatcore` 的仓库。

如果你需要自定义一个 core sdk 的话，参考：

https://wcferry.netlify.app/integrations/node.html#sdk

然后在 初始化 core 时作为参数传递
