### ISSUE TITLE
关于如何获取引用消息的原作者

### ISSUE THREAD

**Issue by PeterChen1997** [wechatferry/wechatferry#12]
目前如果是引用消息，使用封装后，无法获取原来的引用消息的用户信息，想请问下有方法实现吗，原始的数据中是有的，是否可以扩展呢，可以提供思路即可hhh👀

wcferry 里是这么读取的

```
msg.appmsg.refermsg.chatusr
``

感谢作者分享封装的实现，之前用的是 wcferry，python 是在使用不来🤣

**Comment by PeterChen1997** [comment]
通过手动魔改了返回值，在里面带上了，这块原来的 type 限制，确实不好整🤣

**Comment by KeJunMao** [comment]
puppet 吗？其实是做了 refermsg 的解析，你可以代码库里搜一下，但是 wechaty 本身没有相关接口，所以只把消息提取了出来。

但是如果你可以用 messageRawPayload 传递id获取原始消息
