### ISSUE TITLE
room.say 传入 sender 后 @ 错人

### ISSUE THREAD

**Issue by PeterChen1997** [wechatferry/wechatferry#13]
发现在群聊里 sender 写的 A，发出去以后 @ 了 B，这个 B 也不知道是按照什么规则 @ 的，很神奇...

```
await room.say('123', senderA)
```

**Comment by PeterChen1997** [comment]
猜测是在群组内，是不是初始化数据有点问题，没有拉一遍所有的信息🤔

但是给出了依然@ 歪了，感觉有点玄学

**Comment by KeJunMao** [comment]
启动时会拉所有群的所有人到缓存里（默认为内存），支持通过 unstorage 写自定义缓存层，你可以试试写到 fs /redis 来排查一下

但我估计不是这个问题，需要更多复现步骤

**Comment by PeterChen1997** [comment]
> 启动时会拉所有群的所有人到缓存里（默认为内存），支持通过 unstorage 写自定义缓存层，你可以试试写到 fs /redis 来排查一下
> 
> 但我估计不是这个问题，需要更多复现步骤

好咧，我后面再看看

**Comment by KeJunMao** [comment]
由于缺少精准复现步骤，暂时关闭，欢迎随时 open

**Comment by xihan123** [comment]
我也遇到这个问题了，目前来看是群内成员多？我试了打印接收到的消息，群昵称和微信名称是没错的，但是使用room.say就会at错人

也重启过，但是下一秒也会出现

还发现使用这个的at显示的目标的个人微信名称，而不是群昵称，正常at是显示群昵称的
