### ISSUE TITLE
@wechatferry/core调用getContactInfo失败程序会停止

### ISSUE THREAD

**Issue by 184177677** [wechatferry/wechatferry#16]
// 监听微信消息
wcf.on('message', async (msg: WxMsg) => {
  console.log('message:', msg.type);
  console.log('sender:', msg.sender);
  // 只要调用getContactInfo程序就停 Stopping Wechatferry...   ✔ Wechatferry stopped!
  // const contactInfo = await wcf.getContactInfo(msg.sender);
  // console.log(contactInfo);
});

**Comment by KeJunMao** [comment]
此问题来自上游，https://github.com/lich0821/WeChatFerry/issues/196

推荐你使用 agent 的方法，从数据库中查询。
