### ISSUE TITLE
版本对应wechat客户端的版本说明

### ISSUE THREAD

**Issue by atorber** [wechatferry/wechatferry#18]
对应wechatferry版本支持哪个版本的wechat客户端，有必要说明一下

**Comment by KeJunMao** [comment]
现在在 release 处会提到对应的版本，当然是手动的，欢迎贡献一个自动化方案。

**Comment by atorber** [comment]
语义化版本号，在wechatferry的版本命名中加入WeChatFerry、WeChat版本信息，例如0.391027.3924.xxx.xxx，代表支持WeChat: [3.9.10.27](https://github.com/tom-snow/wechat-windows-versions/releases/tag/v3.9.10.27)和WeChatFerry: [39.2.4](https://github.com/lich0821/WeChatFerry/releases/tag/v39.2.4)的版本，第一位代表wechatferry的主版本号，最后边代表wechatferry的次要版本号、修复版本号

**Comment by atorber** [comment]
> 现在在 release 处会提到对应的版本，当然是手动的，欢迎贡献一个自动化方案。

另外也可以在readme里边使用大版本号对应WeChat客户端版本进行管理，重点是对外声明WeChat客户端版本与wechatferry npm包版本号的对应关系，例如 

|wechatferry|客户端版本|
|--|--|
|v0.1.x|[3.9.10.27](https://github.com/tom-snow/wechat-windows-versions/releases/tag/v3.9.10.27)|
|v0.2.x|[3.9.11.25](https://github.com/tom-snow/wechat-windows-versions/releases/tag/v3.9.11.25)|

可以参考https://github.com/wechaty/puppet-xp的做法
![image](https://github.com/user-attachments/assets/afb08175-dcd0-4dca-958b-6b19b7de3280)

**Comment by KeJunMao** [comment]
目前还在 0.0.x 版本，我也没想好啥时候发布 0.1.x

**Comment by KeJunMao** [comment]
> 语义化版本号，在wechatferry的版本命名中加入WeChatFerry、WeChat版本信息，例如0.391027.3924.xxx.xxx，代表支持WeChat: [3.9.10.27](https://github.com/tom-snow/wechat-windows-versions/releases/tag/v3.9.10.27)和WeChatFerry: [39.2.4](https://github.com/lich0821/WeChatFerry/releases/tag/v39.2.4)的版本，第一位代表wechatferry的主版本号，最后边代表wechatferry的次要版本号、修复版本号

这个太细了，不是很喜欢
